### ISSUE TITLE
Does this really require BLAS and LAPACK?

### ISSUE THREAD

**Issue by igrep** [OctopiChalmers/dragen#3]
README says:

> Please make sure you have BLAS and LAPACK installed in your system before compiling.

But no problem happened when I tried to run `stack test` without installing them.
The test was successfully built.

Why does README say that?

**Comment by igrep** [comment]
Looks like that you *used to* depend on BLAS and LAPACK: https://github.com/OctopiChalmers/dragen/commit/628fad86248d5e7699976e1174bf81625ff9ddc2

So can I delete the line from README?

**Comment by agustinmista** [comment]
Hi! 
Indeed, we _used_ to depend on those system libraries. So. yes! feel free to submit a PR whenever you want!
